# Generated by Django 5.0.6 on 2024-05-28 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Imagen_area',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Principal.area')),
            ],
            options={
                'db_table': 'imagen_area',
            },
        ),
        migrations.CreateModel(
            name='Imagen_inmueble',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Principal.inmueble')),
            ],
            options={
                'db_table': 'imagen_inmueble',
            },
        ),
    ]
