# Generated by Django 5.0.6 on 2024-06-03 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='propietario',
        ),
        migrations.AlterModelTable(
            name='inmuebleasesor',
            table='InmuebleAsesor',
        ),
        migrations.AlterModelTable(
            name='inmueblepropietario',
            table='InmueblePropietario',
        ),
    ]
