# Generated by Django 5.0.6 on 2024-06-01 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentos',
            old_name='asesor',
            new_name='asesor_id',
        ),
        migrations.RenameField(
            model_name='documentos',
            old_name='inmueble',
            new_name='inmueble_id',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='estado',
            field=models.CharField(choices=[('En venta', 'En venta'), ('En alquiler', 'En alquiler'), ('Finalizado', 'Finalizado')], default='En venta', max_length=20),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='ubicacion',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='usuario',
            name='descripcion',
            field=models.CharField(null=True),
        ),
        migrations.CreateModel(
            name='Inmueble_usuario',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tipo_persona', models.CharField(choices=[('Asesor', 'Asesor'), ('Propietario', 'Propietario'), ('Director General', 'Director General')], default='Propietario', max_length=20)),
                ('inmueble_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Principal.inmueble')),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
