# Generated by Django 5.0.6 on 2024-06-03 02:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Principal', '0002_remove_inmueble_propietario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
