# Generated by Django 5.0.6 on 2024-06-01 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Principal', '0002_rename_asesor_documentos_asesor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InmuebleAsesor',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('inmueble_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Principal.inmueble')),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InmueblePropietario',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('inmueble_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Principal.inmueble')),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Inmueble_usuario',
        ),
    ]
