# Generated by Django 5.0.6 on 2024-05-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Principal', '0003_usuario_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
    ]
