# Generated by Django 5.0.6 on 2024-06-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Principal', '0003_alter_inmueble_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='direccion',
            field=models.CharField(default=' '),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='latitud',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='longitud',
            field=models.FloatField(default=0.0),
        ),
    ]
