# Generated by Django 5.0.6 on 2024-06-10 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Principal', '0004_remove_inmueble_ubicacion_inmueble_direccion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inmueble',
            table=None,
        ),
    ]
