# Generated by Django 5.0.6 on 2024-06-10 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Principal', '0005_alter_inmueble_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inmueble',
            table='Inmueble',
        ),
    ]
