# Generated by Django 5.0.6 on 2024-05-30 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Principal', '0005_usuario_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
